export { default as About } from './About';
export { default as Cat } from './Cat';
export { default as Contact } from './Contact';
export { default as Dog } from './Dog';
export { default as DogCourse } from './DogCourse';
export { default as Home } from './Home';
export { default as Horse } from './Horse';
export { default as Lecture } from './Lecture';
export { default as MyMethods } from './MyMethods';
